### ISSUE TITLE
Difference between angle_start/end and angle_min/max

### ISSUE THREAD

**Issue by GuyWithCookies** [SICKAG/sick_safetyscanners#94]
Hi,

We are seeing a discrepancy between the `angle_start`/`angle_end` parameters that we define in our launch files and the `angle_min`/`angle_max` values that are published to the `/sick_safetyscanners/scan`.

We configured the `angle_min` and `angle_max` parameters as follows in the launch file:
```
<arg name="angle_start" value="-1.54462" />
<arg name="angle_end" value="1.46608" />
```

However, in the topic we got the values that (slightly) differ:
```
 ---
header: 
  seq: 31290
  stamp: 
    secs: 1642777942
    nsecs: 553113978
  frame_id: "laser_scanner_base_front_link"
angle_min: -1.6118247509002686
angle_max: 1.5312420129776
angle_increment: 0.008954579941928387
time_increment: 4.3000000005122274e-05
scan_time: 0.029999999329447746
range_min: 0.10000000149011612
range_max: 40.0
```

We use three different safety scanners (microScan3) - for all we have this discrepancy.
We use the latest master (commit d4afb838) of this package.

Is this discrepancy expected? If so - what is the differences in the definition of `angle_[min|max]` and `angle_[min|max]`?
